cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: bucket-june-2025


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
  ssl:
    enabled: false
  tomcat:
    connection-timeout: 20000
    max-connections: 10000
